// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tyulhdzrlmkyzmjxegio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5dWxoZHpybG1reXptanhlZ2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyMDM4MjAsImV4cCI6MjA3MTc3OTgyMH0.EoR-7MbuXlvaVQiH3o_COf-IpHAyr_33LH4_kXHcW3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});